name: galaxybox-publish

on:
  push:
    tags:
      - 'v*'  # Triggers on tags starting with 'v' (e.g., v1.0.0, v2.1.3)

permissions:
  contents: write
  id-token: write  # For PyPI trusted publishing

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    name: "Build and publish package to PyPI"
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build package
        run: |
          uv build

      - name: Verify build
        run: |
          ls -la dist/
          uv run twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true

  create_release:
    needs: build_and_publish
    runs-on: ubuntu-latest
    name: "Create GitHub Release"
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.version.outputs.version }}
          body: |
            Changes in this Release
            - Automatically generated from commit history
            - See CHANGELOG.md for detailed changes
          draft: false
          prerelease: false
          generate_release_notes: true
          files: dist/*
